### ISSUE TITLE
Duplicate port defined in LissajousLFO

### ISSUE THREAD

**Issue by cschol** [almostEric/FrozenWasteland#42]
```
#0  0x00007f51a6f8de97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f51a6f8f801 in __GI_abort () at abort.c:79
#2  0x00007f51a6f7f39a in __assert_fail_base (fmt=0x7f51a71067d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x55e365619720 "input->portId != input2->portId", file=file@entry=0x55e3656195a0 "src/app/ModuleWidget.cpp", line=line@entry=466, function=function@entry=0x55e365619980 <rack::app::ModuleWidget::addInput(rack::app::PortWidget*)::__PRETTY_FUNCTION__> "void rack::app::ModuleWidget::addInput(rack::app::PortWidget*)") at assert.c:92
#3  0x00007f51a6f7f412 in __GI___assert_fail (assertion=assertion@entry=0x55e365619720 "input->portId != input2->portId", file=file@entry=0x55e3656195a0 "src/app/ModuleWidget.cpp", line=line@entry=466, function=function@entry=0x55e365619980 <rack::app::ModuleWidget::addInput(rack::app::PortWidget*)::__PRETTY_FUNCTION__> "void rack::app::ModuleWidget::addInput(rack::app::PortWidget*)") at assert.c:101
#4  0x000055e36534abb6 in rack::app::ModuleWidget::addInput(rack::app::PortWidget*) (this=this@entry=0x55e3675ce480, input=<optimized out>) at src/app/ModuleWidget.cpp:466
#5  0x00007f519c9f3a22 in LissajousLFOWidget::LissajousLFOWidget(LissajousLFO*) (this=0x55e3675ce480, module=0x0) at src/LissajousLFO.cpp:430
#6  0x00007f519c9f3e8a in rack::plugin::Model* rack::createModel<LissajousLFO, LissajousLFOWidget>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::TModel::createModuleWidgetNull() (this=0x55e366f607b0) at /home/cschol/src/Rack-SDK/Rack-SDK/include/helpers.hpp:35
#7  0x000055e36533f70a in rack::app::ModelBox::createPreview() (this=0x55e3675126d0) at src/app/ModuleBrowser.cpp:177
#8  0x000055e36533f70a in rack::app::ModelBox::draw(rack::widget::Widget::DrawArgs const&) (this=0x55e3675126d0, args=...) at src/app/ModuleBrowser.cpp:206
#9  0x000055e36535ade9 in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) (this=0x55e3673bf520, args=...) at src/widget/Widget.cpp:174
#10 0x000055e36535ade9 in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) (this=0x55e3673bc1b0, args=...) at src/widget/Widget.cpp:174
#11 0x000055e36535ade9 in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) (this=0x55e3673bc0d0, args=...) at src/widget/Widget.cpp:174
#12 0x000055e36535ade9 in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) (this=this@entry=0x55e3673bf410, args=...) at src/widget/Widget.cpp:174
#13 0x000055e3653199ad in rack::ui::ScrollWidget::draw(rack::widget::Widget::DrawArgs const&) (this=0x55e3673bf410, args=...) at src/ui/ScrollWidget.cpp:31
#14 0x000055e36535ade9 in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) (this=0x55e3673c4590, args=...) at src/widget/Widget.cpp:174
#15 0x000055e36535ade9 in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) (this=0x55e3673bbac0, args=...) at src/widget/Widget.cpp:174
#16 0x000055e36535ade9 in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) (this=0x55e366fa6710, args=...) at src/widget/Widget.cpp:174
#17 0x000055e3653085cd in rack::Window::run() (this=0x55e366fa3370) at src/window.cpp:385
#18 0x000055e365281635 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:186
```

```
diff --git a/src/LissajousLFO.cpp b/src/LissajousLFO.cpp
index b205dd7..3bb2c5b 100644
--- a/src/LissajousLFO.cpp
+++ b/src/LissajousLFO.cpp
@@ -435,7 +435,6 @@ struct LissajousLFOWidget : ModuleWidget {
                addOutput(createOutput<PJ301MPort>(Vec(86, 338), module, LissajousLFO::OUTPUT_3));
                addOutput(createOutput<PJ301MPort>(Vec(126, 338), module, LissajousLFO::OUTPUT_4));
                addOutput(createOutput<PJ301MPort>(Vec(158, 338), module, LissajousLFO::OUTPUT_5));     
-               addOutput(createOutput<PJ301MPort>(Vec(158, 338), module, LissajousLFO::OUTPUT_5));     
                addOutput(createOutput<PJ301MPort>(Vec(190, 338), module, LissajousLFO::OUTPUT_6));     
                addOutput(createOutput<PJ301MPort>(Vec(222, 338), module, LissajousLFO::OUTPUT_7));     
                addOutput(createOutput<PJ301MPort>(Vec(254, 338), module, LissajousLFO::OUTPUT_8));   
```

**Comment by cschol** [comment]
```
-               addInput(createInput<PJ301MPort>(Vec(229, 298), module, LissajousLFO::SKEWX1_INPUT));
-               addInput(createInput<PJ301MPort>(Vec(264, 298), module, LissajousLFO::SKEWY1_INPUT));
+               addInput(createInput<PJ301MPort>(Vec(229, 298), module, LissajousLFO::SKEWX2_INPUT));
+               addInput(createInput<PJ301MPort>(Vec(264, 298), module, LissajousLFO::SKEWY2_INPUT));
```
